apiVersion: v1
kind: Service
metadata:
  name: greeting-service
  namespace: stg
  labels:
    app: greeting-service
spec:
  selector:
    app: greeting-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
