apiVersion: kargo.akuity.io/v1alpha1
kind: ProjectConfig
metadata:
  name: hello-world
  namespace: hello-world
spec:
  promotionPolicies:
    - stageSelector:
        name: dev
      autoPromotionEnabled: true
