apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: hello-world
  namespace: hello-world
spec:
  interval: 1m0s
  subscriptions:
    - image:
        repoURL: ghcr.io/jerry-leung/hello-world
        imageSelectionStrategy: NewestBuild
        allowTagsRegexes:
          - ^sha-
