apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world-dev
  namespace: argocd
  annotations:
    kargo.akuity.io/authorized-stage: hello-world:dev
spec:
  project: default
  source:
    repoURL: https://github.com/Jerry-Leung/hello-world-config.git
    targetRevision: master
    path: k8s/hello-world/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world-stg
  namespace: argocd
  annotations:
    kargo.akuity.io/authorized-stage: hello-world:stg
spec:
  project: default
  source:
    repoURL: https://github.com/Jerry-Leung/hello-world-config.git
    targetRevision: master
    path: k8s/hello-world/stg
  destination:
    server: https://kubernetes.default.svc
    namespace: stg
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: greeting-service-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Jerry-Leung/hello-world-config.git
    targetRevision: master
    path: k8s/greeting-service/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: greeting-service-stg
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Jerry-Leung/hello-world-config.git
    targetRevision: master
    path: k8s/greeting-service/stg
  destination:
    server: https://kubernetes.default.svc
    namespace: stg
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Jerry-Leung/hello-world-config.git
    targetRevision: master
    path: k8s/kafka
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world-kargo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Jerry-Leung/hello-world-config.git
    targetRevision: master
    path: k8s/kargo
  destination:
    server: https://kubernetes.default.svc
    namespace: hello-world
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
